### ISSUE TITLE
If the path contains Chinese characters, it will prompt that the file cannot be read

### ISSUE THREAD

**Issue by zhaixiaowai** [pornel/pngquant#275] opened 2017-11-16 03:05 UTC
pngquant --force  "e:\我的设备\下载区\pngquant-windows\pngquant\1.png" --ext ".min.png" --quality 50-90  --speed 1
  error: cannot open e:\我的设备\下载区\pngquant-windows\pngquant\1.png for reading

**Comment by pornel** [comment] 2017-11-16 13:49
It is a known problem. Duplicate of #265

**Closed** 2017-11-27 16:05 UTC
