### ISSUE TITLE
'gamma value does not match sRGB' when linking with libpng 1.6

### ISSUE THREAD

**Issue by Ackar** [pornel/pngquant#114] opened 2014-08-22 21:51 UTC
I'm trying to use pngquant on a large range of images from the web. When linking pngquant with libpng 1.6 I get an `error: gamma value does not match sRGB` on some images and the resulting image is 0B in size.
This happens only with the `--skip-if-larger` option enabled.

It does not seem to reproduce when compiled with Cocoa or libpng 1.2.

Here are a few images for which it happens:
[Image 1](https://cloud.githubusercontent.com/assets/1406778/4017842/b372f314-2a44-11e4-8445-e7d9e4023993.png)
[Image 2](https://cloud.githubusercontent.com/assets/1406778/4017841/b372d5b4-2a44-11e4-9198-c95973eb67a5.png)
[Image 3](https://cloud.githubusercontent.com/assets/1406778/4017845/b3776002-2a44-11e4-9b1a-2e69269327f1.png)
[Image 4](https://cloud.githubusercontent.com/assets/1406778/4017843/b376905a-2a44-11e4-9af2-c71a97635f1b.png)
[Image 5](https://cloud.githubusercontent.com/assets/1406778/4017844/b376d33a-2a44-11e4-9d43-c1de33a21060.png)

If reading from a file and not from stdin the error isn't displayed but the output file is still empty.

**Comment by pornel** [comment] 2015-04-06 19:34
I can't reproduce it any more, so hopefully it's been fixed in 8b9f0e3e709dc8a2fe951547e6a76bd5986a9384

**Closed by pornel** 2015-04-06 19:34 UTC
