### ISSUE TITLE
overwrite of input file fails v2.3.1; worked w/ v2.1.1 [Windows binary]

### ISSUE THREAD

**Issue by f06yBEAST** [pornel/pngquant#150] opened 2015-04-05 20:11 UTC
Drag & drop png-file to Windows batch script ...

pngquant.exe --ext .png --force --verbose 256 %1

... works @ v2.1.1; fails @ v2.3.1

**Comment by pornel** [comment] 2015-04-05 21:45
Dupe of  #140

**Closed** 2015-04-05 21:45 UTC
